### ISSUE TITLE
Заголовок вкладки в терминале

### ISSUE THREAD

**Issue by MsNatali** [ensi-platform/elc#1]
Было бы удобно при заходе в elc bash чтобы на вкладке терминала выводилось название сервиса

![image](https://user-images.githubusercontent.com/8089373/160783526-752d598f-3bee-443f-8ef7-6dc605592523.png)

**Comment by MadridianFox** [comment]
Этого можно добиться добавив строчку 
```
printf '\033]2;$(hostname)\a'
```
в .bashrc проекта
