### ISSUE TITLE
В файлах сборки прописан адрес https://github.com/madridianfox/elc

### ISSUE THREAD

**Issue by bereza-evgenij** [ensi-platform/elc#19]
В файлах сборки прописан адрес https://github.com/madridianfox/elc вместо адреса текущей репы. Из-за этого при сборке из исходников возникает ошибка
![изображение](https://github.com/ensi-platform/elc/assets/7606944/c839d2f1-9f9d-4224-8289-c818112d37d7)
![изображение](https://github.com/ensi-platform/elc/assets/7606944/7382d343-8226-4992-92b0-219233ec980e)

**Comment by MadridianFox** [comment]
@bereza-evgenij спасибо за внимательность, название неймспейса изменено в версии 0.2.11
Однако это косметическое изменение и старый неймспейс не был причиной проблемы.
Попытка скачать текущий модуль при выполнении команды `go get` - это поведение старой версии go. Очень старой. Обратите внимание что для сборки требуется go версии не ниже 1.19

В связи с этим закрываю issue. Если обновление версии go не поможет, переоткройте issue
