### ISSUE TITLE
Выполнение git хуков падает с ошибкой про TTY

### ISSUE THREAD

**Issue by MadridianFox** [ensi-platform/elc#7]
Окружение: windows 10, WSL2, Ubuntu 20.04, Docker desktop.
При попытке сделать коммит падает хук.
Падает с такой ошибкой
```
Run hook in ELC
the input device is not a TTY
exit status 1
```
Ошибка появилась после обновления Docker Desktop до версии 4.8.2

**Comment by MadridianFox** [comment]
**Workaround:** вручную отредактировать скрипты хуков (.git/hooks/pre-commit и т.д.) - прописать там вызов команды в контейнере без проброса TTY.
Например, если было
`elc --mode=hook .git_hooks/pre-push/test-code.sh`
то должно стать
`elc compose exec -T -u $(id -u):$(id -g) -w /var/www app .git_hooks/pre-push/test-code.sh`
а для модулей
`elc compose exec -T -u $(id -u):$(id -g) -w $PWD app .git_hooks/pre-push/test-code.sh`

**Comment by mtyrtov** [comment]
Тоже самое и без WSL

Ubuntu 22.04 LTS, Docker version 20.10.17, build 100c701

**Comment by MadridianFox** [comment]
В версии 0.2.3 в команду exec добавлен флаг --no-tty,
теперь он выставляется при генерации скриптов хуков. Это должно помочь.
